# Generated by Django 4.0.3 on 2022-03-07 17:02

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', djgeojson.fields.PointField()),
            ],
        ),
    ]
